DELIMITER %

-- USUARIO

CREATE PROCEDURE usuario_Create(IN PARAM_NOME VARCHAR(100), IN PARAM_EMAIL VARCHAR(100), IN PARAM_SENHA VARCHAR(32))
BEGIN
    IF (PARAM_EMAIL REGEXP '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$')
    AND (CHAR_LENGTH(PARAM_SENHA) >= 6)
    AND NOT EXISTS (SELECT 1 FROM usuario WHERE email = PARAM_EMAIL) THEN
        INSERT INTO usuario(nome, email, senha) VALUES (PARAM_NOME, PARAM_EMAIL, PARAM_SENHA);
    END IF;
END%

CREATE PROCEDURE usuario_Update(IN PARAM_ID INT, IN PARAM_NOME VARCHAR(100), IN PARAM_EMAIL VARCHAR(100), IN PARAM_SENHA VARCHAR(32))
BEGIN
    IF (PARAM_EMAIL REGEXP '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$')
    AND (CHAR_LENGTH(PARAM_SENHA) >= 6)
    AND EXISTS (SELECT 1 FROM usuario WHERE id = PARAM_ID) THEN
        UPDATE usuario SET nome = PARAM_NOME, email = PARAM_EMAIL, senha = PARAM_SENHA WHERE id = PARAM_ID;
    END IF;
END%

CREATE PROCEDURE usuario_Delete(IN PARAM_ID INT)
BEGIN
    IF EXISTS (SELECT 1 FROM usuario WHERE id = PARAM_ID) THEN
        DELETE FROM usuario WHERE id = PARAM_ID;
    END IF;
END%

-- CONECTIONS

CREATE PROCEDURE conections_Create(IN PARAM_NOME VARCHAR(100), IN PARAM_CAN_ACTIVE BOOLEAN, IN PARAM_IS_ACTIVE BOOLEAN, IN PARAM_ID_USUARIO INT)
BEGIN
    IF EXISTS (SELECT 1 FROM usuario WHERE id = PARAM_ID_USUARIO)
    AND NOT EXISTS (SELECT 1 FROM conections WHERE nome = PARAM_NOME AND id_usuario = PARAM_ID_USUARIO) THEN
        INSERT INTO conections(nome, can_Active, is_Active, id_usuario) VALUES (PARAM_NOME, PARAM_CAN_ACTIVE, PARAM_IS_ACTIVE, PARAM_ID_USUARIO);
    END IF;
END%

CREATE PROCEDURE conections_Update(IN PARAM_ID INT, IN PARAM_NOME VARCHAR(100), IN PARAM_CAN_ACTIVE BOOLEAN, IN PARAM_IS_ACTIVE BOOLEAN, IN PARAM_ID_USUARIO INT)
BEGIN
    IF EXISTS (SELECT 1 FROM conections WHERE id = PARAM_ID)
    AND EXISTS (SELECT 1 FROM usuario WHERE id = PARAM_ID_USUARIO) THEN
        UPDATE conections SET nome = PARAM_NOME, can_Active = PARAM_CAN_ACTIVE, is_Active = PARAM_IS_ACTIVE, id_usuario = PARAM_ID_USUARIO WHERE id = PARAM_ID;
    END IF;
END%

CREATE PROCEDURE conections_Delete(IN PARAM_ID INT)
BEGIN
    IF EXISTS (SELECT 1 FROM conections WHERE id = PARAM_ID) THEN
        DELETE FROM conections WHERE id = PARAM_ID;
    END IF;
END%

-- DISPOSITIVOS

CREATE PROCEDURE dispositivos_Create(IN PARAM_NOME VARCHAR(100), IN PARAM_TIPO VARCHAR(50), IN PARAM_ID_USUARIO INT)
BEGIN
    IF EXISTS (SELECT 1 FROM usuario WHERE id = PARAM_ID_USUARIO)
    AND NOT EXISTS (SELECT 1 FROM dispositivos WHERE nome = PARAM_NOME AND id_usuario = PARAM_ID_USUARIO) THEN
        INSERT INTO dispositivos(nome, tipo, id_usuario) VALUES (PARAM_NOME, PARAM_TIPO, PARAM_ID_USUARIO);
    END IF;
END%

CREATE PROCEDURE dispositivos_Update(IN PARAM_ID INT, IN PARAM_NOME VARCHAR(100), IN PARAM_TIPO VARCHAR(50), IN PARAM_ID_USUARIO INT)
BEGIN
    IF EXISTS (SELECT 1 FROM dispositivos WHERE id = PARAM_ID)
    AND EXISTS (SELECT 1 FROM usuario WHERE id = PARAM_ID_USUARIO) THEN
        UPDATE dispositivos SET nome = PARAM_NOME, tipo = PARAM_TIPO, id_usuario = PARAM_ID_USUARIO WHERE id = PARAM_ID;
    END IF;
END%

CREATE PROCEDURE dispositivos_Delete(IN PARAM_ID INT)
BEGIN
    IF EXISTS (SELECT 1 FROM dispositivos WHERE id = PARAM_ID) THEN
        DELETE FROM dispositivos WHERE id = PARAM_ID;
    END IF;
END%

-- DISPOSITIVOS_CONECTIONS

CREATE PROCEDURE dispositivos_conections_Create(IN PARAM_ID_CONECTIONS INT, IN PARAM_ID_DISPOSITIVOS INT)
BEGIN
    IF EXISTS (SELECT 1 FROM conections WHERE id = PARAM_ID_CONECTIONS)
    AND EXISTS (SELECT 1 FROM dispositivos WHERE id = PARAM_ID_DISPOSITIVOS)
    AND NOT EXISTS (SELECT 1 FROM dispositivos_conections WHERE id_conections = PARAM_ID_CONECTIONS AND id_dispositivos = PARAM_ID_DISPOSITIVOS) THEN
        INSERT INTO dispositivos_conections(id_conections, id_dispositivos) VALUES (PARAM_ID_CONECTIONS, PARAM_ID_DISPOSITIVOS);
    END IF;
END%

CREATE PROCEDURE dispositivos_conections_Delete(IN PARAM_ID_CONECTIONS INT, IN PARAM_ID_DISPOSITIVOS INT)
BEGIN
    IF EXISTS (SELECT 1 FROM dispositivos_conections WHERE id_conections = PARAM_ID_CONECTIONS AND id_dispositivos = PARAM_ID_DISPOSITIVOS) THEN
        DELETE FROM dispositivos_conections WHERE id_conections = PARAM_ID_CONECTIONS AND id_dispositivos = PARAM_ID_DISPOSITIVOS;
    END IF;
END%

-- INFO

CREATE PROCEDURE info_Create(IN PARAM_ID INT, IN PARAM_E_B INT, IN PARAM_E_R INT, IN PARAM_TIMER INT, IN PARAM_M_ER INT, IN PARAM_V_MER INT, IN PARAM_M_VMER INT)
BEGIN
    IF (PARAM_E_B > 0) AND (PARAM_E_R >= 0) AND (PARAM_TIMER > 0)
    AND EXISTS (SELECT 1 FROM conections WHERE id = PARAM_ID)
    AND NOT EXISTS (SELECT 1 FROM info WHERE id = PARAM_ID) THEN
        INSERT INTO info(id, E_b, E_r, timer, M_er, V_mer, M_vmer) VALUES (PARAM_ID, PARAM_E_B, PARAM_E_R, PARAM_TIMER, PARAM_M_ER, PARAM_V_MER, PARAM_M_VMER);
    END IF;
END%

CREATE PROCEDURE info_Update(IN PARAM_ID INT, IN PARAM_E_B INT, IN PARAM_E_R INT, IN PARAM_TIMER INT, IN PARAM_M_ER INT, IN PARAM_V_MER INT, IN PARAM_M_VMER INT)
BEGIN
    IF (PARAM_E_B > 0) AND (PARAM_E_R >= 0) AND (PARAM_TIMER > 0)
    AND EXISTS (SELECT 1 FROM info WHERE id = PARAM_ID) THEN
        UPDATE info SET E_b = PARAM_E_B, E_r = PARAM_E_R, timer = PARAM_TIMER, M_er = PARAM_M_ER, V_mer = PARAM_V_MER, M_vmer = PARAM_M_VMER WHERE id = PARAM_ID;
    END IF;
END%

CREATE PROCEDURE info_Delete(IN PARAM_ID INT)
BEGIN
    IF EXISTS (SELECT 1 FROM info WHERE id = PARAM_ID) THEN
        DELETE FROM info WHERE id = PARAM_ID;
    END IF;
END%

DELIMITER ;
