DELIMITER %

CREATE PROCEDURE usuario_Controller(IN ACAO TEXT, IN PARAM_ID INT, IN PARAM_NOME VARCHAR(100), IN PARAM_EMAIL VARCHAR(100), IN PARAM_SENHA VARCHAR(32))
BEGIN
    IF (ACAO = 'Create') THEN
        CALL usuario_Create(PARAM_NOME, PARAM_EMAIL, PARAM_SENHA);
    ELSEIF (ACAO = 'Update') THEN
        CALL usuario_Update(PARAM_ID, PARAM_NOME, PARAM_EMAIL, PARAM_SENHA);
    ELSEIF (ACAO = 'Delete') THEN
        CALL usuario_Delete(PARAM_ID);
    ELSEIF (ACAO = 'Index') THEN
        SELECT * FROM index_usuario;
    END IF;
END%

CREATE PROCEDURE conections_Controller(IN ACAO TEXT, IN PARAM_ID INT, IN PARAM_NOME VARCHAR(100), IN PARAM_CAN_ACTIVE BOOLEAN, IN PARAM_IS_ACTIVE BOOLEAN, IN PARAM_ID_USUARIO INT)
BEGIN
    IF (ACAO = 'Create') THEN
        CALL conections_Create(PARAM_NOME, PARAM_CAN_ACTIVE, PARAM_IS_ACTIVE, PARAM_ID_USUARIO);
    ELSEIF (ACAO = 'Update') THEN
        CALL conections_Update(PARAM_ID, PARAM_NOME, PARAM_CAN_ACTIVE, PARAM_IS_ACTIVE, PARAM_ID_USUARIO);
    ELSEIF (ACAO = 'Delete') THEN
        CALL conections_Delete(PARAM_ID);
    ELSEIF (ACAO = 'Index') THEN
        SELECT * FROM index_conections;
    END IF;
END%

CREATE PROCEDURE dispositivos_Controller(IN ACAO TEXT, IN PARAM_ID INT, IN PARAM_NOME VARCHAR(100), IN PARAM_TIPO VARCHAR(50), IN PARAM_ID_USUARIO INT)
BEGIN
    IF (ACAO = 'Create') THEN
        CALL dispositivos_Create(PARAM_NOME, PARAM_TIPO, PARAM_ID_USUARIO);
    ELSEIF (ACAO = 'Update') THEN
        CALL dispositivos_Update(PARAM_ID, PARAM_NOME, PARAM_TIPO, PARAM_ID_USUARIO);
    ELSEIF (ACAO = 'Delete') THEN
        CALL dispositivos_Delete(PARAM_ID);
    ELSEIF (ACAO = 'Index') THEN
        SELECT * FROM index_dispositivos;
    END IF;
END%

CREATE PROCEDURE dispositivos_conections_Controller(IN ACAO TEXT, IN PARAM_ID_CONECTIONS INT, IN PARAM_ID_DISPOSITIVOS INT)
BEGIN
    IF (ACAO = 'Create') THEN
        CALL dispositivos_conections_Create(PARAM_ID_CONECTIONS, PARAM_ID_DISPOSITIVOS);
    ELSEIF (ACAO = 'Delete') THEN
        CALL dispositivos_conections_Delete(PARAM_ID_CONECTIONS, PARAM_ID_DISPOSITIVOS);
    ELSEIF (ACAO = 'Index') THEN
        SELECT * FROM index_dispositivos_conections;
    END IF;
END%

CREATE PROCEDURE info_Controller(IN ACAO TEXT, IN PARAM_ID INT, IN PARAM_E_B INT, IN PARAM_E_R INT, IN PARAM_TIMER INT, IN PARAM_M_ER INT, IN PARAM_V_MER INT, IN PARAM_M_VMER INT)
BEGIN
    IF (ACAO = 'Create') THEN
        CALL info_Create(PARAM_ID, PARAM_E_B, PARAM_E_R, PARAM_TIMER, PARAM_M_ER, PARAM_V_MER, PARAM_M_VMER);
    ELSEIF (ACAO = 'Update') THEN
        CALL info_Update(PARAM_ID, PARAM_E_B, PARAM_E_R, PARAM_TIMER, PARAM_M_ER, PARAM_V_MER, PARAM_M_VMER);
    ELSEIF (ACAO = 'Delete') THEN
        CALL info_Delete(PARAM_ID);
    ELSEIF (ACAO = 'Index') THEN
        SELECT * FROM index_info;
    END IF;
END%

DELIMITER ;
